# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x0c\x62\x61se_package\"\x1d\n\ractionrequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1e\n\x0e\x61\x63tionresponse\x12\x0c\n\x04text\x18\x01 \x01(\t2U\n\nFormatData\x12G\n\x08\x44oFormat\x12\x1b.base_package.actionrequest\x1a\x1c.base_package.actionresponse\"\x00\x62\x06proto3')



_ACTIONREQUEST = DESCRIPTOR.message_types_by_name['actionrequest']
_ACTIONRESPONSE = DESCRIPTOR.message_types_by_name['actionresponse']
actionrequest = _reflection.GeneratedProtocolMessageType('actionrequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:base_package.actionrequest)
  })
_sym_db.RegisterMessage(actionrequest)

actionresponse = _reflection.GeneratedProtocolMessageType('actionresponse', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONRESPONSE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:base_package.actionresponse)
  })
_sym_db.RegisterMessage(actionresponse)

_FORMATDATA = DESCRIPTOR.services_by_name['FormatData']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIONREQUEST._serialized_start=28
  _ACTIONREQUEST._serialized_end=57
  _ACTIONRESPONSE._serialized_start=59
  _ACTIONRESPONSE._serialized_end=89
  _FORMATDATA._serialized_start=91
  _FORMATDATA._serialized_end=176
# @@protoc_insertion_point(module_scope)
